services:
  flights-service:
    image: 635520162216.dkr.ecr.ap-south-1.amazonaws.com/flights-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flights-service
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flights-service
    restart: unless-stopped
